----LISTAR CATALOGOS (TABLAS)----
SELECT *FROM pg_catalog.pg_tables;

---LISTAR TABLAS Y VISTAS DE UNA BASE DE DATOS-----
SELECT
	t1.TABLE_NAME,
    t1.COLUMN_NAME AS columna_nombre,
    t1.COLUMN_DEFAULT AS columna_defecto,
    t1.IS_NULLABLE AS columna_nulo,
    t1.DATA_TYPE AS columna_tipo_dato,
    COALESCE(t1.NUMERIC_PRECISION,
    t1.CHARACTER_MAXIMUM_LENGTH) AS columna_longitud,
    PG_CATALOG.COL_DESCRIPTION(t2.OID,
    t1.DTD_IDENTIFIER::int) AS columna_descripcion,
    t1.DOMAIN_NAME AS columna_dominio
FROM 
    INFORMATION_SCHEMA.COLUMNS t1
    INNER JOIN PG_CLASS t2 ON (t2.RELNAME = t1.TABLE_NAME)
--WHERE 
  --  t1.TABLE_SCHEMA = '[NOMBRE_ESQUEMA]' AND
   -- t1.TABLE_NAME = 'Articulo'
ORDER BY
    t1.ORDINAL_POSITION;
	
-----CONOCER LA ESTRCTURUA DE UNA TABLA---
SELECT *
FROM information_schema.tables --seleccionamos la información del esquema 
--WHERE table_schema='public' --las tablas se encuentran en el esquema publico
--AND table_type='Articulo'; 


-----CONOCER LOS INDICES DE LAS TABLAS-----

select *
from pg_indexes
 -- where schemaname = 'sde'
  order by schemaname, tablename, indexname, tablespace;

---------ORM (MER)---------------------------
/*TABLAS SON NO RELACIONADAS
1 TABLA MAXIMO DEBE TENER HASTA 8 INDICES,10,14,20
PLANES DE EJECUCION (AYUDAN A DETERMINAR LA CONSULTA)
*/

----ORM (MER)
---COMO OBTENER LAS TABLAS RELACIONADAS----
SELECT
    t1.CONSTRAINT_TYPE AS tipo_restriccion,
    t2.COLUMN_NAME AS columna_nombre,
    t1.CONSTRAINT_NAME AS restriccion_nombre,
    t4.CONSTRAINT_NAME AS restriccion_referencia_nombre,
    t4.TABLE_NAME AS tabla_referencia,
    t4.COLUMN_NAME AS columna_referencia
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS t1
    LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE t2
    ON t1.CONSTRAINT_CATALOG = t2.CONSTRAINT_CATALOG
    AND t1.CONSTRAINT_SCHEMA = t2.CONSTRAINT_SCHEMA
    AND t1.CONSTRAINT_NAME = t2.CONSTRAINT_NAME
    LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS t3
    ON t1.CONSTRAINT_CATALOG = t3.CONSTRAINT_CATALOG
    AND t1.CONSTRAINT_SCHEMA = t3.CONSTRAINT_SCHEMA
    AND t1.CONSTRAINT_NAME = t3.CONSTRAINT_NAME
    LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE t4
    ON t3.UNIQUE_CONSTRAINT_CATALOG = t4.CONSTRAINT_CATALOG
    AND t3.UNIQUE_CONSTRAINT_SCHEMA = t4.CONSTRAINT_SCHEMA
    AND t3.UNIQUE_CONSTRAINT_NAME = t4.CONSTRAINT_NAME
--WHERE
--    t1.TABLE_SCHEMA = '[NOMBRE_ESQUEMA]' AND
 --   t1.TABLE_NAME = '[NOMBRE_TABLA]' AND
--    t2.COLUMN_NAME = '[NOMBRE_COLUMNA]'
ORDER BY
    t1.CONSTRAINT_TYPE DESC;


select *from public."Articulo"
